### ISSUE TITLE
list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Tom303-afk** [SimVascular/Tools#2]
Good evening,

Thank you for giving us this great tool.
I tried to apply it to a mesh I made in Simvascular and I got the following error:

Traceback (most recent call last):
  File "Mesh-converter.py", line 182, in <module>
    convert_to_dolfin_xdmf(**read_command_line())
  File "Mesh-converter.py", line 138, in convert_to_dolfin_xdmf
    N = msh_vtp.cells["triangle"].shape[0]
TypeError: list indices must be integers or slices, not str

Can I overcome this problem somehow?

With kind regards,

**Comment by ktbolt** [comment]
No recent activity here so closing for now.
